### ISSUE TITLE
Invalid dependency tmp in grunt-bower-trask

### ISSUE THREAD

**Issue by natrem** [sasaplus1/generator-flowtime#1]
Hello,

I used your generator and had an issue when running grunt bower:install because of a [known incompatibility in tmp module](https://github.com/bower/bower/issues/1404).
I updated grunt-bower-task to ^0.4.0 and it fixed my issue.

Do you still maintain this generator (no offense meant it's just that it did not evolve recently)?
If so I can create a pull request or you can change the version in the template.
I saw other dependencies are not up-to-date but I'm fairly new on node and yeoman so I didn't test it yet.

Regards,
natrem

**Comment by sasaplus1** [comment]
Hello, thank you using for this generator :)

I'm not using this generator. Would you PR for me?

**Comment by sasaplus1** [comment]
#2
